"""add username and role to users

Revision ID: 6b3a9b164538
Revises: bb0ed316cb0f
Create Date: 2026-06-14 04:57:07.253476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b3a9b164538'
down_revision: Union[str, None] = 'bb0ed316cb0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=50), nullable=False, comment='Login uchun nom, masalan: admin'))
    op.add_column('users', sa.Column('role', sa.String(length=20), nullable=False, comment="Foydalanuvchi roli: 'admin' yoki 'reviewer'"))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'role')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
