"""initial_models

Revision ID: bb0ed316cb0f
Revises: 
Create Date: 2026-06-02 19:53:08.048188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb0ed316cb0f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False, comment="Muallif to'liq ismi"),
    sa.Column('birth_year', sa.Integer(), nullable=True, comment="Tug'ilgan yili"),
    sa.Column('death_year', sa.Integer(), nullable=True, comment="Vafot etgan yili (agar vafot etgan bo'lsa)"),
    sa.Column('description', sa.Text(), nullable=True, comment="Muallif haqida qisqacha ma'lumot"),
    sa.Column('image', sa.String(length=500), nullable=True, comment='Muallif rasmining URL yoki fayl nomi'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authors_full_name'), 'authors', ['full_name'], unique=False)
    op.create_table('publishers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Nashriyot nomi'),
    sa.Column('founded_year', sa.Integer(), nullable=True, comment='Tashkil etilgan yili'),
    sa.Column('image', sa.String(length=500), nullable=True, comment='Logo yoki belgi rasmi'),
    sa.Column('description', sa.Text(), nullable=True, comment="Nashriyot haqida ma'lumot"),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publishers_name'), 'publishers', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False, comment='Telefon raqam, masalan: +998901234567'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_table('books',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False, comment='Kitob nomi'),
    sa.Column('description', sa.Text(), nullable=True, comment="Kitob haqida qisqacha ma'lumot"),
    sa.Column('published_year', sa.Integer(), nullable=True, comment='Nashr qilingan yili'),
    sa.Column('pages', sa.Integer(), nullable=True, comment='Betlar soni'),
    sa.Column('sold_count', sa.Integer(), nullable=False, comment='Sotilgan nusxalar soni'),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False, comment="Kitob narxi (so'mda)"),
    sa.Column('rating', sa.Float(), nullable=False, comment='Reyting (0.0 — 5.0)'),
    sa.Column('image', sa.String(length=500), nullable=True, comment='Kitob muqovasi rasmi URL yoki fayl nomi'),
    sa.Column('author_id', sa.Integer(), nullable=False, comment='Muallif ID'),
    sa.Column('publisher_id', sa.Integer(), nullable=True, comment='Nashriyot ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['publisher_id'], ['publishers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_books_title'), 'books', ['title'], unique=False)
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'book_id', name='uq_user_book_favorite')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    op.drop_index(op.f('ix_books_title'), table_name='books')
    op.drop_table('books')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_publishers_name'), table_name='publishers')
    op.drop_table('publishers')
    op.drop_index(op.f('ix_authors_full_name'), table_name='authors')
    op.drop_table('authors')
    # ### end Alembic commands ###
